version: '3.8'
services:
  db:
    image: postgres:16
    env_file:
      - ./.env
    ports:
      - '5432:5432'
  api:
    image: rub21/osm-sandbox-user:v10
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - '8000:8000'
    working_dir: /app
