{{- if .Values.db.enabled -}}
{{- if .Values.db.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    app: {{ template "osm-sandbox.name" . }}
    component: db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  capacity:
    storage: {{ .Values.db.persistenceDisk.AWS_ElasticBlockStore_size }}
  awsElasticBlockStore:
    volumeID: {{ .Values.db.persistenceDisk.AWS_ElasticBlockStore_volumeID }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pv-claim
  labels:
    app: {{ template "osm-sandbox.name" . }}
    component: db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  storageClassName: ""
  volumeName: {{ .Release.Name }}-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistenceDisk.AWS_ElasticBlockStore_size }}
{{- end }}
{{- end }}
