environment: dashboard
serviceType: ClusterIP
db:
  enabled: true
  image:
    name: postgres
    tag: 16
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: db
  env:
    POSTGRES_DB: db_dashboard
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "1234"
  persistenceDisk:
    enabled: false
    accessMode: ReadWriteOnce
    mountPath: /var/lib/postgresql/data
    subPath: postgresql-db
    # In case cloudProvider: aws
    AWS_ElasticBlockStore_volumeID: vol-09964172ef71bc8e8
    AWS_ElasticBlockStore_size: 200Gi
  resources:
    enabled: false
    requests:
      memory: "10Gi"
      cpu: "5"
    limits:
      memory: "10Gi"
      cpu: "5"
  sharedMemorySize: 16Mi
  # livenessProbeExec: true
dashboard:
  enabled: true
  image:
    name: rub21/osm-sandbox-user
    tag: v8
  ingressDomain: dashboard.osm-sandbox.org
  env:
    OSM_CLIENT_ID: 'xyz'
    OSM_CLIENT_SECRET: 'xyz'
    REDIRECT_URI: 'https://dashboard.osm-sandbox.org/oauth_authorization'
    OSM_INSTANCE_URL: 'https://www.openstreetmap.org'
    OSM_INSTANCE_SCOPES: 'read_prefs'
    # PG data
    SANDBOX_PG_DB_PORT: "5432"
    SANDBOX_PG_DB_USER: postgres
    SANDBOX_PG_DB_PASSWORD: "1234"
    SANDBOX_PG_DB_NAME: openstreetmap
    ENVIRONMENT: 'dev'
    # Main domain
    SANDBOX_DOMAIN: 'osm-sandbox.org'
  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "512Mi"
      cpu: "1"
  nodeSelector:
    enabled: false
    label_key: nodegroup_type
    label_value: db
